name: agora_rtm
description: Flutter plugin for Agora RTM SDK.
version: 1.0.1
homepage: 'https://www.agora.io'
repository: 'https://github.com/AgoraIO/Flutter-RTM'
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.6'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: 0.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agorartm
        pluginClass: AgoraRtmPlugin
      ios:
        pluginClass: AgoraRtmPlugin
      web:
        pluginClass: AgoraRtmWebPlugin
        fileName: src/web/agora_rtm_web_plugin.dart
